
# TODO:
#       - start using this instead of openhab
#       - influx
#           https://community.home-assistant.io/t/home-assistant-community-add-on-influxdb/54491
#       - duck dns
#       - phillips hue
#           https://www.home-assistant.io/integrations/hue/
#           https://stackoverflow.com/questions/65948825/cant-send-command-to-ble-device-philips-hue-bulb-connection-drops
#           https://github.com/walter5138/hue_ble_bash


default_config:
group: !include groups.yaml
automation: !include_dir_merge_list automation/
# script: !include scripts.yaml
# scene: !include scenes.yaml

logger:
  default: info

device_tracker:
  - platform: sky_hub
    host: 192.168.1.254
    interval_seconds: 200
    new_device_defaults:
      track_new_devices: false

person: !include person.yaml

lovelace:
    mode: yaml
    resources:
      - url: /local/button-card.js
        type: module

    # # Add more dashboards
    # dashboards:
      # lovelace-generated: # Needs to contain a hyphen (-)
        # mode: yaml
        # filename: notexist.yaml
        # title: Generated
        # icon: mdi:tools
        # show_in_sidebar: true
        # require_admin: true
      # lovelace-hidden:
        # mode: yaml
        # title: hidden
        # show_in_sidebar: true
        # filename: ui/new.yaml

# media_player:
  # - platform: braviatv
    # host: 192.168.1.24

switch:
  - platform: mqtt
    state_topic: "stat/plugs/plug1/POWER"
    command_topic: "cmnd/plugs/plug1/POWER"
    name: plug1

  - platform: mqtt
    state_topic: "stat/plugs/plug2/POWER"
    command_topic: "cmnd/plugs/plug2/POWER"
    name: plug2

  - platform: mqtt
    state_topic: "stat/plugs/plug3/POWER"
    command_topic: "cmnd/plugs/plug3/POWER"
    name: plug3
    retain: true

  # send singnal to switch boiler on/off
  - platform: mqtt
    # state_topic: "state/sensor/heating"
    command_topic: "cmnd/sensor/heating"
    name: Heating Switch
    unique_id: heating_switch
    retain: true
    payload_on: 1
    payload_off: 0

sensor:
  - platform: mqtt
    # name: "Temperature"
    name: "794296394_temperature"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.temperature }}"
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "794296394_adc_temperature"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.adc_temp }}"
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "794296394_humidity"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.humidity / 1000 | round }}"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "794296394_pressure"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.pressure | float / 100 | int }}"
    unit_of_measurement: "hPa"

  - platform: mqtt
    name: "794296394_gas_resistance"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.gas_res }}"
    unit_of_measurement: "Ohm"

  - platform: mqtt
    name: "794296394_air_quality"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.iaq }}"
    unit_of_measurement: ""

  - platform: mqtt
    name: "794296394_air_quality_2"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.iaq2 }}"
    unit_of_measurement: " "

  - platform: mqtt
    name: "794296394_last_updated"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.timestamp | timestamp_custom('%d/%m/%y %H:%M:%S') }}"

  # sensors used for displaying input values to prevent changing in ui
  - platform: template
    sensors:
      i_heating_temp_set:
        friendly_name: Heating Temp Set
        value_template: '{{ states("input_number.heating_temp_set") }}'
        # unit: ""  # degrees
      i_heating:
        friendly_name: Heating
        value_template: '{{ states("group.g_heating") }}'

input_number:
  heating_on_temp:
    name: Heating On Temp (C)
    initial: 20
    min: 5
    max: 35

  heating_off_temp:
    name: Heating Off Temp (C)
    initial: 14
    min: 5
    max: 35

  max_ext_temp:
    name: Max External Temperature (C)
    initial: 12
    min: 5
    max: 20

  heating_temp_set:
    name: Heating Temperature (C)
    # value: "{{ states(input_number.heating_off_temp) }}"
    min: 0
    max: 100

  heating_boost_timer:
    name: Heating Boost Timer (min)
    initial: 60
    min: 30
    max: 180

  heating_pwm_timer:
    name: Heating PWM Timer (min)
    initial: 240
    min: 100
    max: 400

  heating_pwm_duty_cycle:
    name: Heating PWM Duty Cycle (%)
    # unit: percent
    initial: 20
    min: 10
    max: 50

  heating_pwm_period:
    name: Heating PWM Period (min)
    initial: 30
    min: 0
    max: 60

input_boolean:
  # track if heating is on
  heating:
    name: Heating
  # track heating manually switched on
  heating_boost:
    name: Heating Boost
  heating_pwm:
    name: Heating PWM
  # track heating switched on by schedule
  heating_sched:
    name: Heating Scheduled
  heating_sched_enable:
    name: Heating Scheduled Enabled
  # track heating time/day trigger to abstract schedule rules
  heating_sched_trigger:
    name: Heating Sched Trigger


############################### DEBUG ENTITIES ################################

input_text:
  debug_text:
    initial: "-"

input_boolean test_b:
  name: test 11

input_number wait:
    name: wait
    min: 100
    max: 2000

sensor i_debug:
  platform: template
  sensors:
    i_debug:
      friendly_name: debug text
      value_template: >
        {{ states('input_text.debug_text') }}
        # {% set entity = 'input_boolean.heating_boost' %}
        # {% set ent_str = entity.replace("boolean", "number") + "_timer" %}
        # {{ states(ent_str) | int }}
        # {% set ent_str = entity.replace("boolean", "number") %}
        # {{ states(entity) | int }}

    # {% set entity = "input_number.{}_timer".format("heating_boost") %}
    # {{ states(entity) | int }}

switch test_s:
  platform: mqtt
  name: test1
  command_topic: "stat/sensor/t1"

switch test2:
  - platform: mqtt
    name: test2
    unique_id: test2
    command_topic: "stat/sensor/t2"
