
# TODO:
#       - start using this instead of openhab
#       - influx
#           https://community.home-assistant.io/t/home-assistant-community-add-on-influxdb/54491
#       - duck dns
#       - phillips hue
#           https://www.home-assistant.io/integrations/hue/
#           https://stackoverflow.com/questions/65948825/cant-send-command-to-ble-device-philips-hue-bulb-connection-drops
#           https://github.com/walter5138/hue_ble_bash
#       - youtube
#           https://community.home-assistant.io/t/play-youtube-on-smart-tv/101407/43
#           https://www.home-assistant.io/integrations/media_extractor/
#       - nicer sysinfo
#           https://community.home-assistant.io/t/history-graph-with-min-and-max-horizontal-lines/119677/5
#       - group for light + TV
#       - config examples
#           https://github.com/geekofweek/homeassistant
#       - upgrade
#           python -m pip install --upgrade homeassistant homeassistant-cli
#               check following is merge
#               https://github.com/home-assistant-ecosystem/home-assistant-cli/issues/332
#       - on battery - 794296394
#           480mAh - 2021-11-20T15:38 -> 2021-12-20T16:57
#           400mAh - 2021-12-20T18:43 ->

# BACKUP:
#   create backup:
#       backup_file=/tmp/hass_`date +"%FT%T"`.bundle
#       git bundle create <backup_file> <branch>
#       scp backup_file <user>@<host>:backup/hass-backup
#   recreate from bundle
#       git clone `bundle` repo

# dependencies:
#   apt:
#       - mosquitto-clients, mosquitto, python3-rpi.gpio, python3-spidev,
#       - python3-paho-mqtt, python3-dbus, python3-gi, letsencrypt, libsqlite3-dev, git
#       - nginx (reverse proxy)
#           https://iotechonline.com/home-assistant-access-with-nginx-proxy-and-lets-encrypt/?cn-reloaded=1
#   python-3.10 (compile/install)
#   pip venv:
#       - telebot, gatt

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

# Individual options represented by default_config
#cloud:
#logbook:
#map:
#ssdp:
#zeroconf:

api:
config:
energy:
frontend:
history:
input_datetime:
input_select:
mobile_app:
sun:
system_health:
updater:
zone:

homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/London
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # customize: !include customize.yaml
  # external_url: !secret external_url
  # internal_url: !secret internal_url
  packages: !include_dir_named packages/

  allowlist_external_dirs:
    - /home/ghost/homeassistant/conf

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        # - fd00::/8
        # - fe80::/8
      allow_bypass_login: true
      trusted_users:
        192.168.1.0/24:
          # David
          - f566f23f959541a7b8060b9a6d842e93
          # Luke
          - dcff045ad0ac4aed8b4ba261fc679118
          # Sara
          -  ebe476cf675d4efc8dbcd66bae1a9114
    - type: homeassistant

# http:
  # # api_password: !secret http:password
  # use_x_forwarded_for: true
  # trusted_proxies:
    # - 127.0.0.1
    # # - 192.168.1.80
  # ip_ban_enabled: true
  # login_attempts_threshold: 5

automation: !include_dir_merge_list automation/
group: !include groups.yaml
light: !include lights.yaml
lovelace: !include ui/lovelace.yaml
person: !include person.yaml
recorder: !include recorder.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

logger:
  default: warning

device_tracker:
  - platform: bt_home_hub_5
    host: 192.168.1.254
    interval_seconds: 200
    consider_home: 300
    new_device_defaults:
      track_new_devices: false


utility_meter:
  hourly_electricity:
    source: sensor.electric_cost_today
    cycle: hourly
  daily_electricity:
    source: sensor.electric_cost_today
    cycle: daily
  monthly_electricity:
    source: sensor.electric_cost_today
    cycle: monthly
  annual_electricity:
    source: sensor.electric_consumption_year
    cycle: yearly
  hourly_gas:
    source: sensor.gas_cost_today
    cycle: hourly
  daily_gas:
    source: sensor.gas_cost_today
    cycle: daily
  monthly_gas:
    source: sensor.gas_cost_today
    cycle: monthly
  annual_gas:
    source: sensor.gas_consumption_year
    cycle: yearly


mqtt:
    broker: homeassistant
    port: 1883


# https://www.dummylabs.com/post/2019-01-13-influxdb-part1/
influxdb:
    api_version: 1
    ssl: false
    host: 192.168.1.99
    port: 8086
    username: openhab
    password: openhab
    database: openhab_db
    # exclude:
    # entity_globs: '*'
    include:
        entities:
            - switch.heating_switch
            - input_number.heating_temp_set
              # TODO: should include via group.g_heating
            - switch.heating_boost
            - switch.heating_sched
            - switch.heating_pwm

            - group.g_present
        entity_globs:
            - switch.plug*
            - sensor.794296394_*
    # domains:
      # - group.g_plugs
      # - switch


# setup via ui
# weather:
  # - platform: openweathermap
    # api_key: !secret openweathermap_key


switch:
  - platform: mqtt
    state_topic: "stat/plugs/plug1/POWER"
    command_topic: "cmnd/plugs/plug1/POWER"
    name: plug1

  - platform: mqtt
    state_topic: "stat/plugs/plug2/POWER"
    command_topic: "cmnd/plugs/plug2/POWER"
    name: plug2

  - platform: mqtt
    state_topic: "stat/plugs/plug3/POWER"
    command_topic: "cmnd/plugs/plug3/POWER"
    name: plug3
    retain: true


binary_sensor:
  - platform: workday
    country: UK


sensor:
  - platform: mqtt
    name: "794296394_temperature"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.temperature }}"
    unit_of_measurement: "°C"
    device_class: temperature
    force_update: true
    # unique_id: "794296394_temperature"
    device:
        identifiers: "794296394"
        name: "jeenode zero 794296394"

  - platform: mqtt
    name: "794296394_adc_temperature"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.adc_temp }}"
    unit_of_measurement: "°C"
    device_class: temperature
    force_update: true
    # unique_id: "794296394_adc_temperature"
    device:
        identifiers: "794296394"
        name: "794296394"

  - platform: mqtt
    name: "794296394_humidity"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.humidity / 1000 | round }}"
    unit_of_measurement: "%"
    device_class: humidity
    force_update: true
    device:
        identifiers: "794296394"
        name: "794296394"

  - platform: mqtt
    name: "794296394_pressure"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.pressure | float / 100 | int }}"
    unit_of_measurement: "hPa"
    device_class: pressure
    force_update: true
    device:
        identifiers: "794296394"
        name: "794296394"

  - platform: mqtt
    name: "794296394_gas_resistance"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.gas_res }}"
    unit_of_measurement: "Ohm"
    force_update: true
    device:
        identifiers: "794296394"
        name: "794296394"

  - platform: mqtt
    name: "794296394_air_quality"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.iaq }}"
    unit_of_measurement: "."
    device_class: aqi
    force_update: true
    device:
        identifiers: "794296394"
        name: "794296394"

  - platform: mqtt
    name: "794296394_air_quality_2"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.iaq2 }}"
    unit_of_measurement: "."
    device_class: aqi
    force_update: true
    device:
        identifiers: "794296394"
        name: "794296394"

  - platform: mqtt
    name: "794296394_last_updated"
    state_topic: "state/sensor/794296394"
    value_template: "{{ value_json.timestamp | timestamp_custom('%d/%m/%y %H:%M:%S') }}"
    device:
        identifiers: "794296394"
        name: "794296394"

  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
      - type: swap_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: last_boot

  - platform: uptime
    scan_interval: 600

  - platform: template
    sensors:
      uptime_ha:
        friendly_name: HA Uptime
        value_template: >
          {{ "%0.1f" | format(
            (as_timestamp(now()) - as_timestamp(states('sensor.uptime')))
            / 3600 / 24) }}

  - platform: template
    sensors:
      uptime_sys:
        friendly_name: Uptime
        value_template: >
          {{ "%0.1f" | format(
             (as_timestamp(now()) - as_timestamp(states('sensor.last_boot')))
             / 3600 / 24) }}

  - platform: filesize
    file_paths:
      - /home/ghost/homeassistant/conf/home-assistant_v2.db


input_boolean:
  # enable holiday mode
  holiday_mode:
    name: Holiday Mode

  switch_off_lr:
    name:  Switch Off
