title: Home
icon: mdi:home
views:
    - !include ui/home.yaml
    - !include ui/sensors.yaml
    - !include ui/weather.yaml
    - !include ui/tv.yaml
    - !include ui/plugs.yaml
    - !include ui/sysinfo.yaml
    - !include ui/settings.yaml
    - !include ui/debug.yaml
