title: Settings
path: settings
cards:
  - type: entities
    title: Heating
    show_header_toggle: false
    entities:
        - input_boolean.heating_sched_enable
        - input_number.heating_on_temp
        - input_number.heating_off_temp
        - input_number.max_ext_temp
        - input_number.heating_boost_timer
        - input_number.heating_pwm_timer
        - input_number.heating_pwm_duty_cycle
        - input_number.heating_pwm_period

  - type: entities
    title: Holiday Mode
    show_header_toggle: false
    entities:
        - input_boolean.holiday_mode

  - type: entities
    title: Energy tariffs
    show_header_toggle: false
    entities:
        - input_number.gas_tariff_rate
        - input_number.electric_tariff_rate
