
title: Home
views:
    - !include home.yaml
    - !include sensors.yaml
    - !include weather.yaml
    - !include tv.yaml
    - !include lukes_tv.yaml
    - !include plugs.yaml
    - !include north_wing.yaml
