
template:
  # abstract sensors name to sensor location
  - sensor:
    - name: sensor_1985242708
      state: 'Door'
  - sensor:
    - name: 1985242708_last_updated
      state: >
        {% set last_updated = states.sensor["1985242708_door_event"].last_updated %}
        {{ last_updated | timestamp_custom("%d-%m-%y %H:%M:%S") }}

sensor:
  - platform: mqtt
    name: "1985242708_door_event"
    state_topic: "state/sensor/1985242708"
    value_template: "{{ value_json.door_event }}"
    force_update: true
    device:
      identifiers: "1985242708"
      name: "bpx 1985242708"
